### ISSUE TITLE
Cannot find module 'telegram-mtproto'

### ISSUE THREAD

**Issue by w1r0x** [matrix-org/matrix-appservice-tg#3]
When I trying to generate registration or start application i get this:

```
# node index.js --generate-registration -f telegram-registration.yaml  -u localhost
/app/node_modules/olm/olm.js:19
"undefined"!==typeof module&&(module.exports=a);process.on("uncaughtException",function(a){if(!(a instanceof T))throw a;});a.inspect=function(){return"[Emscripten Module object]"}}else if(ma)a.print||(a.print=print),"undefined"!=typeof printErr&&(a.printErr=printErr),a.read="undefined"!=typeof read?read:function(){throw"no read() available (jsc?)";},a.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");z("object"===typeof a);return a},"undefined"!=
                                                                                                                ^

Error: Cannot find module 'telegram-mtproto'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/app/lib/TelegramGhost.js:5:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/app/lib/MatrixUser.js:3:21)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/app/lib/Main.js:11:18)
    at Module._compile (module.js:571:32)
```

```
# node -v
v7.10.0

# npm -v
4.2.0
```

npm install log cut
```
UNMET PEER DEPENDENCY webpack@>=0.9 <2 || ^2.1.0-beta || ^2.2.0

npm WARN worker-loader@0.8.0 requires a peer of webpack@>=0.9 <2 || ^2.1.0-beta || ^2.2.0 but none was installed.
```

So it is seems to be telegram-mtproto bug.
I can see `"telegram-mtproto": "leonerd/telegram-mtproto#cf17f2b"` in package.json so there is need to change this after telegram-mtproto fix.

**Comment by ptman** [comment]
Not having this problem. I had a similar complain about prom-client, but `rm -rf node_modules/ && npm install` fixed it
