### ISSUE TITLE
Error: Expected the 'username_template' to contain the string ${ID}

### ISSUE THREAD

**Issue by szclsya** [matrix-org/matrix-appservice-tg#4]
``` 
node index.js --config ./config/telegram-config.yaml --port 8001
Loading config file /home/sya/telematrix/matrix-appservice-tg/config/telegram-config.yaml
Matrix-side listening on port 8001
/home/sya/telematrix/matrix-appservice-tg/node_modules/olm/olm.js:19
"undefined"!==typeof module&&(module.exports=a);process.on("uncaughtException",function(a){if(!(a instanceof T))throw a;});a.inspect=function(){return"[Emscripten Module object]"}}else if(ma)a.print||(a.print=print),"undefined"!=typeof printErr&&(a.printErr=printErr),a.read="undefined"!=typeof read?read:function(){throw"no read() available (jsc?)";},a.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");z("object"===typeof a);return a},"undefined"!=
                                                                                                                ^

Error: Expected the 'username_template' to contain the string ${ID}
    at new Main (/home/sya/telematrix/matrix-appservice-tg/lib/Main.js:62:15)
    at Object.run (/home/sya/telematrix/matrix-appservice-tg/index.js:22:10)
    at Cli._startWithConfig (/home/sya/telematrix/matrix-appservice-tg/node_modules/matrix-appservice-bridge/lib/components/cli.js:180:15)
    at Cli.run (/home/sya/telematrix/matrix-appservice-tg/node_modules/matrix-appservice-bridge/lib/components/cli.js:139:10)
    at Object.<anonymous> (/home/sya/telematrix/matrix-appservice-tg/index.js:24:4)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3
``` 
Node version v7.10.0
npm version v4.2.0

**Comment by szclsya** [comment]
Sloved. Add a ${ID} in the line username_template in `telegram-config.yaml` config file. 
Thanks to @KenOokamiHoro .
