### ISSUE TITLE
Can not start or generate registration

### ISSUE THREAD

**Issue by mrdumpty** [matrix-org/matrix-appservice-tg#8]
matrix@matrix:/opt/tgr/matrix-appservice-tg$ node index.js --generate-registration -f telegram-registration.yaml  -u localhost:9938
/opt/tgr/matrix-appservice-tg/lib/TelegramGhost.js:181
            remove: (...keys) => {
                     ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/opt/tgr/matrix-appservice-tg/lib/MatrixUser.js:3:21)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/opt/tgr/matrix-appservice-tg/lib/Main.js:12:18)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/opt/tgr/matrix-appservice-tg/index.js:4:12)

**Comment by paulbdavis** [comment]
This seems to be an issue of using an outdated node. Try using nodejs >= 6
