### ISSUE TITLE
Failed to join room

### ISSUE THREAD

**Issue by paulbdavis** [matrix-org/matrix-appservice-tg#9]
When trying to invite `@telegrambot:DOMAIN` I get this error

```
telegram-bridge    | ::ffff:172.18.0.6 - - [07/Nov/2017:15:45:50 +0000] "PUT /transactions/11?access_token=<REDACTED> HTTP/1.1" 200 2 "-" "Synapse/0.24.1"
telegram-bridge    | 
telegram-bridge    | [-] POST synapse:8008/_matrix/client/r0/join/!<ROOMID>%3A<DOMAIN> (AS) Body: {}
telegram-bridge    | [-] POST synapse:8008/_matrix/client/r0/join/!<ROOMID>%3A<DOMAIN> (AS) HTTP null Error: {}
telegram-bridge    | Failed:  Error: Failed to join room
telegram-bridge    |     at /app/node_modules/matrix-appservice-bridge/lib/components/intent.js:491:26
telegram-bridge    |     at _rejected (/app/node_modules/q/q.js:864:24)
telegram-bridge    |     at /app/node_modules/q/q.js:890:30
telegram-bridge    |     at Promise.when (/app/node_modules/q/q.js:1142:31)
telegram-bridge    |     at Promise.promise.promiseDispatch (/app/node_modules/q/q.js:808:41)
telegram-bridge    |     at /app/node_modules/q/q.js:624:44
telegram-bridge    |     at runSingle (/app/node_modules/q/q.js:137:13)
telegram-bridge    |     at flush (/app/node_modules/q/q.js:125:13)
telegram-bridge    |     at _combinedTickCallback (internal/process/next_tick.js:73:7)
telegram-bridge    |     at process._tickCallback (internal/process/next_tick.js:104:9)
telegram-bridge    | Error: Failed to join room
telegram-bridge    |     at /app/node_modules/matrix-appservice-bridge/lib/components/intent.js:491:26
telegram-bridge    |     at _rejected (/app/node_modules/q/q.js:864:24)
telegram-bridge    |     at /app/node_modules/q/q.js:890:30
telegram-bridge    |     at Promise.when (/app/node_modules/q/q.js:1142:31)
telegram-bridge    |     at Promise.promise.promiseDispatch (/app/node_modules/q/q.js:808:41)
telegram-bridge    |     at /app/node_modules/q/q.js:624:44
telegram-bridge    |     at runSingle (/app/node_modules/q/q.js:137:13)
telegram-bridge    |     at flush (/app/node_modules/q/q.js:125:13)
telegram-bridge    |     at _combinedTickCallback (internal/process/next_tick.js:73:7)
telegram-bridge    |     at process._tickCallback (internal/process/next_tick.js:104:9)
telegram-bridge    | ::ffff:172.18.0.6 - - [07/Nov/2017:15:46:12 +0000] "PUT /transactions/12?access_token=<REDACTED> HTTP/1.1" 200 2 "-" "Synapse/0.24.1"
```

**Comment by paulbdavis** [comment]
Looking into it further, it seems the `joinRoom` request is returning `e.errcode !== "M_FORBIDDEN"` and triggering that error return [here](https://github.com/matrix-org/matrix-appservice-bridge/blob/5c9b204c6b8d5b314f349b64b9529fcdcd98c1a5/lib/components/intent.js#L491). Is there some configuration I am missing on the homeserver?

**Comment by paulbdavis** [comment]
Turns out the issue is that you need to have `http://` in the homeserver url
